#!/usr/bin/ruby
# encoding: utf-8

libdir = File.join(File.dirname(__FILE__), '../lib')
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

require 'storage'
require 'user_factory'
require 'model/user'
require 'model/user_data'
require 'model/user_score'

redis = Redis.new

UserData.storage(redis).all_in_batches do |ud|
  score = UserScore.storage(redis).scores_for(ud.id).map {|o| o['score'] }.inject(&:+).to_i
  ud.inc_month_score(score - ud['month_score'])
end
